const PI = Math.PI;
console.log("The value of PI is:", PI);
console.log(Math.round(PI));
console.log(Math.floor(PI));
console.log(Math.ceil(PI));
console.log(Math.min(-5, 3, 20, 4, 5, 10));
console.log(Math.max(-5, 3, 20, 4, 5, 10));
const randNum = Math.random();
console.log("A random number :", randNum);
const num = Math.floor(Math.random() * 11);
console.log(num)
console.log(Math.abs(-10));
console.log(Math.sqrt(100));
console.log(Math.sqrt(2));
console.log(Math.pow(3, 2));
console.log(Math.E);
console.log(Math.log(2));
console.log(Math.log(10));
console.log(Math.sin(0));
console.log(Math.cos(60));
console.log(Math.cos(0));
console.log(Math.tan(45));
console.log(Math.tan(0));
